platform :ios, '8.2'


use_frameworks!

target "ERP_Swift" do

pod 'Alamofire'
pod 'Kingfisher', '~> 4.5.0'
#pod 'SwiftyJSON', '~> 4.0.0'
pod "Device"
pod 'IQKeyboardManagerSwift'
pod 'SnapKit'
pod "ESPullToRefresh"
pod "ESTabBarController-swift"
pod 'KeychainAccess'
pod 'SwiftyJSONMappable', '~> 1.0.3'
pod 'NVActivityIndicatorView'

end
